# Site settings
title: "Margem da Margem"
description: "Intersecções de filosofia, ética, arte e engenharia de software"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "Thaís Robba"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Editor settings
prose:
  media: "assets"
  
# Third-party services
# just leave empty to disable it
? google_analytics
? disqus_shortname

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
